### ISSUE TITLE
Conveyor Spawner Improvements

### ISSUE THREAD

**Issue by jrgnicho** [swri-robotics/Gilbreth#14]
Below is a list of changes/improvements to be made to the conveyor spawner node:
- The conveyor spawner node currently requires loading each object's urdf description as a ROS parameter.  Consequently, there's a launch file that loads these parameters and an associated configuration yaml that has to be manually synced to match the objects in the launch.  While this approach works, it could become inconvenient on an environment with lots more objects and consequently many more ROS parameters.  Therefore one proposed solution is to have the conveyor spawner node load the object's urdf file directly and use it to create the gazebo object spawn service request.
- The spawning parameters in the [conveyor_objects.yaml](https://github.com/swri-robotics/gilbreth/blob/kinetic-devel/gilbreth_support/config/conveyor_objects.yaml) such as the initial pose and placement randomization variables are the same for all the objects.  It would be more convenient to rearrange the file structure to allow setting these same parameters on an per object basis for more flexibility.

**Comment by marip8** [comment]
Additional comments from 10/5 meeting
- [x] Documentation for assumptions/randomization/operation of conveyor spawner
- [x] Create new random variable for each randomized parameter
