### ISSUE TITLE
Perception does not publish detected pick point

### ISSUE THREAD

**Issue by jrgnicho** [swri-robotics/Gilbreth#30]
The perception node seems to fail at identifying every object at the moment.
To reproduce just run the application as instructed [here](https://github.com/swri-robotics/gilbreth/blob/kinetic-devel/DEMO.md) and observed the perception terminal window for its console output.

**Comment by lianjunli** [comment]
@jrgnicho When I click 'here', there is no instructions on how to reproduce the bug, could you let me know how to reproduce the issue?

**Comment by jrgnicho** [comment]
It's just the demo instructions https://github.com/swri-robotics/gilbreth/blob/kinetic-devel/DEMO.md

**Comment by lianjunli** [comment]
@jrgnicho I run the demo several times, seems the recognition works fine, do you see the issue every time you run the demo?
![image](https://user-images.githubusercontent.com/28901741/35651435-494d4ce6-06a5-11e8-807c-29e3afc10896.png)

**Comment by jrgnicho** [comment]
That's not what I'm getting, it keeps saying No Correspondance Matching or something along those lines.  I'll try it out on another machine an report.  Did you run this off a clean build and the latest kinetic-devel branch?

**Comment by jrgnicho** [comment]
@lianjunli I just ran it on another system off a clean build and the perception does work.  Robot execution and perhaps planning still fail badly but at least we know the perception piece behaves as expected.  Thanks for reporting your findings.
