### ISSUE TITLE
gilbreth_controller_spawner always fails on the first attempt at starting the simulation.

### ISSUE THREAD

**Issue by mbharatheesha** [swri-robotics/Gilbreth#31]
I have observed that the gilbreth_controller_spawner node always dies on the first attempt at starting the gazebo simulation (times out waiting for controller manager). All subsequent attempts to start the gazebo simulation succeed, provided I let the first attempt to "exit gracefully". By that, I mean, I wait until MoveIt! vents out all its anger via log statements about controller managers not being available and unwillingly gives me the green signal to start planning anyway. Once I terminate this instance of the launch and re-launch the simulation, everything works just fine.

Its a bit weird that the second and subsequent attempts do not time out where as the first one always does! It might be my "slow" hardware that causes this, but I would expect this to happen always in that case. I am running this simulation on a MBP with Intel Core i5 2.5GHz Dual Core, 8GB RAM. 

Any ideas on what could be happening here? Or anyone else having faced the same problem?

**Comment by jrgnicho** [comment]
Try pulling the latest kinetic-devel branch and see if you're still running into that issue.

**Comment by mbharatheesha** [comment]
I just tested the latest changes on kinetic-devel and I still see the same behavior. Fails on the first attempt and succeeds in all subsequent attempts.

**Comment by jrgnicho** [comment]
I would think it's a timeout issue as you say however it's odd that it only occurs the first time.  There may be some gazebo caching that's computationally more expensive the first time around.  One quick solution be to just increase the timeout on the spawner node or staging the demo in three steps: Gazebo bring up -> World Bring up -> Everything Else. That seems cumbersome however specially when restarting makes it go away.

**Comment by dhood** [comment]
Something we found for ARIAC was that gazebo will try to fetch some models into `~/.gazebo/models` on first startup. Maybe you'll see that that directory has some models in it after you run the simulation the first time? (e.g. the `sun` model). If that's the case, for ARIAC our approach was just to make sure all models have been downloaded beforehand.

**Comment by jrgnicho** [comment]
@dhood I checked that directory and found only the `sun` models.  Our setup has most of its models (meshes, gazebo plugins, etc.) fully described in the xacro file, that includes the robot rail too.

**Comment by dhood** [comment]
Even just having 1 model that needs to be downloaded was enough for us to see startup delays on first run. It might not be significant enough to cause the controller manager issues that were mentioned, but that's the only thing I'm aware of that's different for the first gazebo run.

If the issue comes back when you delete `~/.gazebo/models` then that suggests to download delay is related, otherwise probably not

**Comment by mbharatheesha** [comment]
I just got time to test this again. @dhood, you are right. `gzserver` does download `ground_plane` and `sun` models on the first run. And the problem reappears on emptying `~/.gazebo/models`. The delay is about 65s which explains why the `gilbreth_controller_spawner` times out. Thanks for the input.

**Comment by jrgnicho** [comment]
Interesting,  @dhood  or @mbharatheesha sounds like as long as the gazebo models have been cached to  the `~/.gazebo/models` directory then this is no longer an issue?

**Comment by mbharatheesha** [comment]
@jrgnicho: Yes, if `ground_plane` and `sun` models are in `~/.gazebo/models` directory, then this is no longer an issue.

**Comment by jrgnicho** [comment]
I have not observed this issue in a while after after the many PRs that have been merged since it was first reported.  I'll keep this issue opened for a little while in case it resurfaces again.  Thanks for y'all's feedback.

**Comment by dhood** [comment]
From my understanding of the situation, it's going to be something that only new users/installations see, it won't be something that you see on a "dirty" machine.
We got around it in ARIAC by embedding sun and ground plane model equivalents in our world file to remove all dependence on the gazebo model database, which might work for you also, or just let new users know to expect this the first time.

**Comment by jrgnicho** [comment]
Embedding those constructs in the world file should fix it.  I'll create a patch for that  but in the mean time putting a warning somewhere wouldn't hurt.

**Comment by mbharatheesha** [comment]
@dhood: Indeed, this wouldn't be a problem on a "dirty machine", unless one wants to spin up a docker container running this project without mounting the home volumes.
@jrgnicho: That would be nice.

**Comment by jrgnicho** [comment]
@mbharatheesha feel free to create a patch for it.

**Comment by mbharatheesha** [comment]
@jrgnicho: I made the patch and have created a PR for it. Tested it on my system and the controller manager doesn't timeout anymore.

**Comment by jrgnicho** [comment]
Fixed by #44
