### ISSUE TITLE
Unstable object pick pose

### ISSUE THREAD

**Issue by alex07zzz** [swri-robotics/Gilbreth#39]
The output of object recognition is not stable in z-direction, see the following picture. The z-direction's output jumps from 1.03 to 0.92. I observed this behavior in many parts. This behavior makes it pretty hard to tune the parameter for robot to pick up the objects.

![picture1](https://user-images.githubusercontent.com/16554844/35888246-08736b8c-0b65-11e8-8415-dbaaa0877082.png)

**Comment by jrgnicho** [comment]
It looks like it varies by about 11 cm,  It is expected that there will be differences in the computed height even for the same part, but not by that much.
@lianjunli could you take a look?

**Comment by jrgnicho** [comment]
@alex07zzz  which parameter needs tuning?

**Comment by alex07zzz** [comment]
@jrgnicho The parameters in gilbreth_perception/config/model_lists.yaml need tuning. They control the output (pose and orientation) of object recognition.

**Comment by lianjunli** [comment]
@jrgnicho @alex07zzz  Sure I will look into it.

**Comment by jrgnicho** [comment]
@alex07zzz right, I meant the parameters related to the robot pick tuning
@lianjunli  thanks

**Comment by lianjunli** [comment]
@jrgnicho @alex07zzz 
Solved by adding fine alignment step in recognition node, see pull request #40

**Comment by jrgnicho** [comment]
Fixed by #40
