### ISSUE TITLE
MoveIt! Robot in collision by default

### ISSUE THREAD

**Issue by jrgnicho** [swri-robotics/Gilbreth#8]
It appears that the robot is in collision regardless of what pose it's in even when no objects are in collision with it.  To reproduce bring up the demo.launch file in the gilbreth_moveit_config package and drag the robot to a collision free pose.

**Comment by marip8** [comment]
Check out PR #10. I think this should solve those issues

**Comment by jrgnicho** [comment]
@alex07zzz could you test the latest branch for this issue.  The latest merge #10 should've addressed this.

**Comment by alex07zzz** [comment]
Hi Jorge and Michael,

It perfectly solved problems. Really awesome and great helps! Thank you so much.

Best,
Yizhe

在 2017年9月11日，下午5:00，Jorge Nicho <notifications@github.com<mailto:notifications@github.com>> 写道：


@alex07zzz<https://github.com/alex07zzz> could you test the latest branch for this issue. The latest merge #10<https://github.com/swri-robotics/gilbreth/pull/10> should've addressed this.

**Comment by jrgnicho** [comment]
@alex07zzz thanks for checking.
