### ISSUE TITLE
Spawn objects in conveyor

### ISSUE THREAD

**Issue by jrgnicho** [swri-robotics/Gilbreth#9]
There needs to be a node that will automatically spawn objects on the conveyor belt.  It should be configurable in order to control the frequency at which things are spawned and should also allow some randomization on the placement pose of the object.

**Comment by marip8** [comment]
I'll start working on that next week

**Comment by marip8** [comment]
Check out #12

**Comment by jrgnicho** [comment]
#12 addresses this.
